### PR TITLE
ansible: Curl install script first then install parity

### PR DESCRIPTION
**Pull request by fangyi-zhou**

### CODE REVIEW

**Comment by levex** [comment]
Why?

**Comment by fangyi-zhou** [comment]
fatal: [146.169.45.52]: FAILED! => {"changed": true, "cmd": "bash <(curl https://get.parity.io -kL)", "delta": "0:00:00.001233", "end": "2017-11-28 14:53:50.932966", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2017-11-28 14:53:50.931733", "stderr": "/bin/sh: 1: Syntax error: \"(\" unexpected", "stderr_lines": ["/bin/sh: 1: Syntax error: \"(\" unexpected"], "stdout": "", "stdout_lines": []}

**Comment by levex** [comment]
????? it always worked on my end?

**Comment by levex** [comment]
accidental close, sorry!

**Comment by fangyi-zhou** [comment]
try a fresh vm. guaranteed not work

**Pull request merged**
