### PR TITLE
dapp: added histogram for average price of energy from contracts

### PR DESCRIPTION
**Pull request by fangyi-zhou**
Energy price histogram from @egospodinova cherry-picked from a messy branch

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
has some CSS fails, requires bug fix

**Comment by fangyi-zhou** [comment]
Can anyone else have it look? It seems that it is taking a long time to load and CSS didn't fail.

**Comment by egospodinova** [comment]
It takes ages to load because it waits for the contracts to load first. There may be an optimization possible here?

**Comment by fangyi-zhou** [comment]
ah okay.

**Comment by fangyi-zhou** [comment]
I'm considering doing some caching from the server

**Comment by egospodinova** [comment]
Alternatively, we can update the histogram after every contract is queried?

**Comment by fangyi-zhou** [comment]
I'm confused. Is the histogram updated on every contract update?

**Comment by egospodinova** [comment]
Not at the moment. Currently it's only updated once after all the contracts are known when the page loads and that's why it's slow.

**Comment by fangyi-zhou** [comment]
Okay. The plan is to cache the blockchain info at server and front end queries server instead of blockchain directly. We should have some speedup.

**Pull request merged**
