### PR TITLE
simulation-meter: Price is a parameter of the simulation

### PR DESCRIPTION
**Pull request by vincepandolfo**
Usage:
`-P [price]` sets the selling price in the individual simulation

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
What does python do when it serialises big integers? e.g. 10 ** 18 (1 ether)

**Comment by fangyi-zhou** [comment]
Please fix CI

**Comment by vincepandolfo** [comment]
big integers work just fine

**Comment by fangyi-zhou** [comment]
s/Fixed/Fix/

**Pull request merged**
