### PR TITLE
Remove unused bootstrap template

### PR DESCRIPTION
**Pull request by fangyi-zhou**

### CODE REVIEW

**Comment by Norbo11** [comment]
I wouldn't merge this yet, we should contribute to this PR until all of front-end is properly cleaned up (all things nicely split into react components, etc)

**Comment by fangyi-zhou** [comment]
this is to removed unused bootstrap

**Comment by fangyi-zhou** [comment]
I don't know how to move stuff around without breaking it. It makes it non-trivial. Changing difficulty to medium.

Help needed.

**Comment by Norbo11** [comment]
I'll take a look at this stuff now.

**Comment by Norbo11** [comment]
Can merge this now I think.

**Pull request merged**
